-- Script de nettoyage et réinsertion des articles SPAH et SICD
-- Suppression de TOUS les articles de type MP existants
DELETE FROM public.articles WHERE article_type = 'MP';
-- Suppression des emballages SPAH et SICD
DELETE FROM public.articles WHERE family IN ('SPAH', 'SICD');

INSERT INTO public.articles (code, name, article_type, family, unit) VALUES
('SPAH-001', 'Huile alimentaire', 'MP', 'SPAH', 'kg'),
('SPAH-002', 'Bois Sapin', 'MP', 'SPAH', 'kg'),
('SPAH-003', 'COLORANT Bleu', 'MP', 'SPAH', 'kg'),
('SPAH-004', 'COLORANT BASIC ROUGE 4G 200% PETARD', 'MP', 'SPAH', 'kg'),
('SPAH-005', 'Vieux papiers blanc local 1er choix', 'MP', 'SPAH', 'kg'),
('SPAH-006', 'Vieux papiers blanc local 2eme choix', 'MP', 'SPAH', 'kg'),
('SPAH-007', 'Vieux papiers couleur melée local A', 'MP', 'SPAH', 'kg'),
('SPAH-008', 'Vieux papiers couleur melée local B', 'MP', 'SPAH', 'kg'),
('SPAH-009', 'Hypochlorite de calcium', 'MP', 'SPAH', 'kg'),
('SPAH-010', 'Sulfate d''alumine', 'MP', 'SPAH', 'kg'),
('SPAH-011', 'Anti mousse', 'MP', 'SPAH', 'kg'),
('SPAH-012', 'Maximyze', 'MP', 'SPAH', 'kg'),
('SPAH-013', 'Dispersant agent (Polyethylène) FEV 2020', 'MP', 'SPAH', 'kg'),
('SPAH-014', 'Bobine Fabrication 1 pli LYS', 'EMB', 'SPAH', 'kg'),
('SPAH-015', 'Bobine PH EGYPTE 3 20 ECO', 'EMB', 'SPAH', 'kg'),
('SPAH-016', 'Mandrins', 'EMB', 'SPAH', 'kg'),
('SPAH-017', 'KRAFT UNION PAPER', 'MP', 'SPAH', 'kg'),
('SPAH-018', 'JR DOUCY CONFORT-JUMBO ROLL DOUCY CONFORT', 'MP', 'SPAH', 'kg'),
('SPAH-019', 'MANDRIN 130CM', 'EMB', 'SPAH', 'kg'),
('SPAH-020', 'CHUTTE DE X° DOUCY ECO', 'MP', 'SPAH', 'kg'),
('SPAH-021', 'CHUTTE DE X° DOUCY LYS', 'MP', 'SPAH', 'kg'),
('SPAH-022', 'CHUTTE DE X° LYS ROSE', 'MP', 'SPAH', 'kg'),
('SPAH-023', 'BOBINE FABRICATION 1 PLI LYS ROSE', 'EMB', 'SPAH', 'kg'),
('SPAH-024', 'JR Doucy Eco - Jumbo Rolls Doucy Eco', 'MP', 'SPAH', 'kg'),
('SPAH-025', 'JR Doucy Classic- Jumbo Rolls Doucy Classic', 'MP', 'SPAH', 'kg'),
('SPAH-026', 'Colle Ravemul', 'MP', 'SPAH', 'kg'),
('SICD-001', 'Fécule de manioc', 'MP', 'SICD', 'kg'),
('SICD-002', 'REVELATEUR POSIDEV 300g', 'MP', 'SICD', 'kg'),
('SICD-003', 'EPONGES VEGETALES', 'MP', 'SICD', 'kg'),
('SICD-004', 'Plaques Posit 335x488', 'MP', 'SICD', 'kg'),
('SICD-005', 'AGRAFES NOVIS 23/15', 'MP', 'SICD', 'kg'),
('SICD-006', 'Encre flexo UV - Blanche', 'MP', 'SICD', 'kg'),
('SICD-007', 'PCB  blanc une face  80gr', 'MP', 'SICD', 'kg'),
('SICD-008', 'PCB  Blanc double face 250gr', 'MP', 'SICD', 'kg'),
('SICD-009', 'Autocopiant CB Blanc 65*100', 'MP', 'SICD', 'kg'),
('SICD-010', 'Autocopiant CF Rose 65*100', 'MP', 'SICD', 'kg'),
('SICD-011', 'Autocopiant CFB Bleu 65*100', 'MP', 'SICD', 'kg'),
('SICD-012', 'Autocopiant CFB Jaune 65*100', 'MP', 'SICD', 'kg'),
('SICD-013', 'Autocipiant CFB Vert 65*100', 'MP', 'SICD', 'kg'),
('SICD-014', 'Eponge', 'MP', 'SICD', 'kg'),
('SICD-015', 'Cerewax', 'MP', 'SICD', 'kg'),
('SICD-016', 'Colorant jaune Oragnol', 'MP', 'SICD', 'kg'),
('SICD-017', 'Cire d'' Abeille', 'MP', 'SICD', 'kg'),
('SICD-018', 'Miel d''abeille', 'MP', 'SICD', 'kg'),
('SICD-019', 'Sel', 'MP', 'SICD', 'kg'),
('SICD-020', 'Oxyde de Fer', 'MP', 'SICD', 'kg'),
('SICD-021', 'Petrole Ecnes'' s', 'MP', 'SICD', 'kg'),
('SICD-022', 'Gas Oil', 'MP', 'SICD', 'kg'),
('SICD-023', 'Polymer VC0232', 'MP', 'SICD', 'kg'),
('SICD-024', 'Colorant Bleu Roi', 'MP', 'SICD', 'kg'),
('SICD-025', 'Colorant vert Fonce 1017', 'MP', 'SICD', 'kg'),
('SICD-026', 'PEHD', 'MP', 'SICD', 'kg'),
('SICD-027', 'PP SEETEC', 'MP', 'SICD', 'kg'),
('SICD-028', 'Sulfate de soude anhydre /Sodium silicate Accord Commodities', 'MP', 'SICD', 'kg'),
('SICD-029', 'SOUDE CAUSTIQUE 25KG', 'MP', 'SICD', 'kg'),
('SICD-030', 'Sachet Bougie Maronjana Lehibe (5.2*S1.3*29.5cm) 70µ -Sans impression', 'EMB', 'SICD', 'kg'),
('SICD-031', 'Etiquette Bougie 20*5cm PCM 250g', 'EMB', 'SICD', 'kg'),
('SICD-032', 'Verrine', 'EMB', 'SICD', 'kg'),
('SICD-033', 'Bocal 50ml Blanc - AP050CB', 'EMB', 'SICD', 'kg'),
('SICD-034', 'Carton Bougie C40 - (25.4 * 19.4 * 24.6cm)', 'EMB', 'SICD', 'kg'),
('SICD-035', 'CARTON BOUGIE MARONJANA LEHIBE C40 - (26 * 24 * 25)', 'EMB', 'SICD', 'kg'),
('SICD-036', 'Sachet Tadynyl E60 * 550 * 1200 avec impression', 'EMB', 'SICD', 'kg'),
('SICD-037', 'ETIQUETTE TADYNYL', 'EMB', 'SICD', 'kg'),
('SICD-038', 'Carton savon BARRE FOTSY 70g (27x18x14,5)', 'EMB', 'SICD', 'kg'),
('SICD-039', 'Carton savon IR24 (18.4 * 14.1 * 9.2)-Andramena', 'EMB', 'SICD', 'kg'),
('SICD-040', 'Carton savon IR24 (18.4 * 14.1 * 9.2)-Andramena K', 'EMB', 'SICD', 'kg'),
('SICD-041', 'Carton savon IR24 (18.4 * 14.1 * 9.2)-Fotsy K', 'EMB', 'SICD', 'kg'),
('SICD-042', 'Carton savon IR24 (18.4 * 14.1 * 9.2)-Menakely', 'EMB', 'SICD', 'kg'),
('SICD-043', 'Carton savon IR24 (18.4 * 14.1 * 9.2)-Tantely K', 'EMB', 'SICD', 'kg'),
('SICD-044', 'Carton savon IR24 (23 * 15,4 * 11,5) MM-Fotsy', 'EMB', 'SICD', 'kg'),
('SICD-045', 'Carton savon IR24 (23 * 15,4 * 11,5) MM-Menakely', 'EMB', 'SICD', 'kg'),
('SICD-046', 'Carton savon IR24 (23 * 15,4 * 11,5) MM-Tantely', 'EMB', 'SICD', 'kg'),
('SICD-047', 'Carton savon IR24 (23 * 15,4 * 11,5) MM-Tantely MM', 'EMB', 'SICD', 'kg'),
('SICD-048', 'Carton Savon XG (21,6 x 16,3 x 11,5)-Andramena', 'EMB', 'SICD', 'kg'),
('SICD-049', 'Carton Savon XG (21,6 x 16,3 x 11,5)-Fotsy', 'EMB', 'SICD', 'kg'),
('SICD-050', 'Carton Savon XG (21,6 x 16,3 x 11,5)-Menakely', 'EMB', 'SICD', 'kg'),
('SICD-051', 'Carton Savon XG (21,6 x 16,3 x 11,5)-Nanto XG', 'EMB', 'SICD', 'kg'),
('SICD-052', 'Carton Savon XG (21,6 x 16,3 x 11,5)-Tantely', 'EMB', 'SICD', 'kg'),
('SICD-053', 'Carton Savon PM (16,5 x 12,5 x 7)-Andramena', 'EMB', 'SICD', 'kg'),
('SICD-054', 'Carton Savon PM (16,5 x 12,5 x 7)-Menakely', 'EMB', 'SICD', 'kg'),
('SICD-055', 'Carton Savon PM (16,5 x 12,5 x 7)-Nanto PM', 'EMB', 'SICD', 'kg'),
('SICD-056', 'Carton Savon PM (16,5 x 12,5 x 7)-Tantely', 'EMB', 'SICD', 'kg'),
('SICD-057', 'Carton savon Fotsy MM (23 * 15,4 * 11,5) - TYPE D', 'EMB', 'SICD', 'kg'),
('SICD-058', 'Etiquette savon IRIKO  I30', 'EMB', 'SICD', 'kg'),
('SICD-059', 'Carton savon IRIKO  I27', 'EMB', 'SICD', 'kg'),
('SICD-060', 'Carton savon IRIKO  I30', 'EMB', 'SICD', 'kg'),
('SICD-061', 'Carton savon IRIKO  Z27', 'EMB', 'SICD', 'kg'),
('SICD-062', 'Sachet savon BARRE FOTSY 70g', 'EMB', 'SICD', 'kg'),
('SICD-063', 'Sachet savon BARRE FOTSY 150g', 'EMB', 'SICD', 'kg'),
('SICD-064', 'Sachet savon BARRE FOTSY 220g', 'EMB', 'SICD', 'kg'),
('SICD-065', 'Sachet savon BARRE FOTSY 472g', 'EMB', 'SICD', 'kg'),
('SICD-066', 'Carton savon BARRE FOTSY 70g (28.2 x 19.8 x 15.8)', 'EMB', 'SICD', 'kg'),
('SICD-067', 'Carton savon BARRE FOTSY 150g (28.2 x 17.2 x 15.8)', 'EMB', 'SICD', 'kg'),
('SICD-068', 'Carton savon BARRE FOTSY 220g (34 x 17.2 x 15.8)', 'EMB', 'SICD', 'kg'),
('SICD-069', 'Carton savon BARRE FOTSY 472g (34 x 17.2 x 12.2)', 'EMB', 'SICD', 'kg'),
('SICD-070', 'Carton savon 800g-Fotsy', 'EMB', 'SICD', 'kg'),
('SICD-071', 'Carton savon 800g-Nature', 'EMB', 'SICD', 'kg'),
('SICD-072', 'Boite Encaustique 0,50 l - 400cc -Neutre', 'EMB', 'SICD', 'kg'),
('SICD-073', 'Carton Encaustique 36 pots 37*28*16,8', 'EMB', 'SICD', 'kg'),
('SICD-074', 'Carton Encaustique 24 pots 41*31,5*16', 'EMB', 'SICD', 'kg'),
('SICD-075', 'Carton Encaustique 4 seaux 45*22,5,30,5', 'EMB', 'SICD', 'kg'),
('SICD-076', 'Carton Encaustique 36 pots PREMIUM - 37*28*16.8', 'EMB', 'SICD', 'kg'),
('SICD-077', 'Carton Encaustique 24 pots PREMIUM - 41*31.5*16', 'EMB', 'SICD', 'kg'),
('SICD-078', 'Etiquette Encaustique 200cc-Acajou', 'EMB', 'SICD', 'kg'),
('SICD-079', 'Etiquette Encaustique 200cc-Jaune', 'EMB', 'SICD', 'kg'),
('SICD-080', 'Etiquette Encaustique 200cc-Neutre', 'EMB', 'SICD', 'kg'),
('SICD-081', 'Etiquette Encaustique 200cc-Special ciment', 'EMB', 'SICD', 'kg'),
('SICD-082', 'Pot 200cc blanc  sans impression avec couvercle -Acajou', 'EMB', 'SICD', 'kg'),
('SICD-083', 'Pot 200cc blanc  sans impression avec couvercle -Jaune', 'EMB', 'SICD', 'kg'),
('SICD-084', 'Pot 200cc blanc  sans impression avec couvercle -Neutre', 'EMB', 'SICD', 'kg'),
('SICD-085', 'Pot 200cc blanc  sans impression avec couvercle -Special ciment', 'EMB', 'SICD', 'kg'),
('SICD-086', 'Pot 400cc blanc  sans impression avec couvercle -Acajou', 'EMB', 'SICD', 'kg'),
('SICD-087', 'Pot 400cc blanc  sans impression avec couvercle -Jaune', 'EMB', 'SICD', 'kg'),
('SICD-088', 'Pot 400cc blanc  sans impression avec couvercle -Special ciment', 'EMB', 'SICD', 'kg'),
('SICD-089', 'Seaux 3000cc blanc  sans impression avec couvercle-Acajou', 'EMB', 'SICD', 'kg'),
('SICD-090', 'Seaux 3000cc blanc  sans impression avec couvercle-Jaune', 'EMB', 'SICD', 'kg'),
('SICD-091', 'Seaux 3000cc blanc  sans impression avec couvercle-Neutre', 'EMB', 'SICD', 'kg'),
('SICD-092', 'Seaux 3000cc blanc  sans impression avec couvercle-Special ciment', 'EMB', 'SICD', 'kg'),
('SICD-093', 'Etiquette Encaustique 400cc -Acajou', 'EMB', 'SICD', 'kg'),
('SICD-094', 'Etiquette Encaustique 400cc -Jaune', 'EMB', 'SICD', 'kg'),
('SICD-095', 'Etiquette Encaustique 400cc -Special ciment', 'EMB', 'SICD', 'kg'),
('SICD-096', 'Etiquette Encaustique 3000cc-Neutre', 'EMB', 'SICD', 'kg'),
('SICD-097', 'CARTON LIQUIDE VAISSELLE 28.5 X 19.3 X 21.7', 'EMB', 'SICD', 'kg'),
('SICD-098', 'Bouchon Push Pull', 'EMB', 'SICD', 'kg'),
('SICD-099', 'Sachet P06 Neutre (190T S45 x 450 x 35µ)', 'EMB', 'SICD', 'kg'),
('SICD-100', 'Panier - Bougie decorative', 'EMB', 'SICD', 'kg'),
('SICD-101', 'Sac personnalisé 35*40cm', 'EMB', 'SICD', 'kg'),
('SICD-102', 'PAPIER BOBINE 84GR ROULEAU', 'EMB', 'SICD', 'kg'),
('SICD-103', 'PROCESS JAUNE SINT 26', 'MP', 'SICD', 'kg'),
('SICD-104', 'PROCESS MAGENT SINT27', 'MP', 'SICD', 'kg'),
('SICD-105', 'PROCESS ROUGE PANTONE 200C', 'MP', 'SICD', 'kg'),
('SICD-106', 'PROCESS ROUGE PANTONE 187C', 'MP', 'SICD', 'kg'),
('SICD-107', 'PROCESS NOIR SINT 46', 'MP', 'SICD', 'kg'),
('SICD-108', 'PROCESS CYAN SINT 25', 'MP', 'SICD', 'kg'),
('SICD-109', 'VERT P340', 'MP', 'SICD', 'kg'),
('SICD-110', 'ROUGE FEU PANTONE 192C', 'MP', 'SICD', 'kg'),
('SICD-111', 'Calque', 'MP', 'SICD', 'kg'),
('SICD-112', 'gomme Ã©cobidon', 'MP', 'SICD', 'kg'),
('SICD-113', 'alcool isopropilique', 'MP', 'SICD', 'kg'),
('SICD-114', 'eau de mouillage TECHNOVA', 'MP', 'SICD', 'kg'),
('SICD-115', 'PLATE CLEANER TECHNOVA', 'MP', 'SICD', 'kg'),
('SICD-116', 'essence', 'MP', 'SICD', 'kg'),
('SICD-117', 'petrole', 'MP', 'SICD', 'kg'),
('SICD-118', 'Agrafe 23/15', 'MP', 'SICD', 'kg'),
('SICD-119', 'Agrafe 23/10', 'MP', 'SICD', 'kg'),
('SICD-120', 'Encre primaire CYAN boite de 2,5kg', 'EMB', 'SICD', 'kg'),
('SICD-121', 'Encre primaire MAGENTA boite de 2,5kg', 'EMB', 'SICD', 'kg'),
('SICD-122', 'Encre primaire JAUNE boite de 2,5kg', 'EMB', 'SICD', 'kg'),
('SICD-123', 'Encre primaire NOIR boite de 2,5kg', 'EMB', 'SICD', 'kg'),
('SICD-124', 'Massicot Reglette Polar 92', 'MP', 'SICD', 'kg'),
('SICD-125', 'Cageot plastique', 'MP', 'SICD', 'kg'),
('SICD-126', 'Poudre antimaculante regular medium (20 a 40µ)', 'MP', 'SICD', 'kg'),
('SICD-127', 'Plaque 650*550*0,30', 'MP', 'SICD', 'kg'),
('SICD-128', 'Acide Stearique', 'MP', 'SICD', 'kg'),
('SICD-129', 'PARAFFINE  60°- 62°', 'MP', 'SICD', 'kg'),
('SICD-130', 'Palm Fatty acid distillate PFAD', 'MP', 'SICD', 'kg'),
('SICD-131', 'Coco fatty acid distillate CFAD', 'MP', 'SICD', 'kg'),
('SICD-132', 'Parfum citron Klin', 'MP', 'SICD', 'kg'),
('SICD-133', 'Palm Acide Oïl – PAO', 'MP', 'SICD', 'kg'),
('SICD-134', 'Huile de palme rouge', 'MP', 'SICD', 'kg'),
('SICD-135', 'Bondillon Rouge TFM 60%', 'MP', 'SICD', 'kg'),
('SICD-136', 'Bondillon Marron Mariani ( PFAD - CFAD - PAO - SEL - SULFATE )', 'MP', 'SICD', 'kg'),
('SICD-137', 'Bondillon translucide BLANC', 'MP', 'SICD', 'kg'),
('SICD-138', 'Bondillon translucide ROUGE', 'MP', 'SICD', 'kg'),
('SICD-139', 'Bondillon translucide MARRON', 'MP', 'SICD', 'kg'),
('SICD-140', 'TALC 20', 'MP', 'SICD', 'kg'),
('SICD-141', 'Colorant marron Versanyl Brown VT', 'MP', 'SICD', 'kg'),
('SICD-142', 'PARAFFIN WAX 3-5%', 'MP', 'SICD', 'kg'),
('SICD-143', 'SLES', 'MP', 'SICD', 'kg'),
('SICD-144', 'KRAFT 180g MARRON', 'MP', 'SICD', 'kg'),
('SICD-145', 'Colorant en pourdre pour savon - Couleur Noire', 'MP', 'SICD', 'kg'),
('SICD-146', 'Colorant en pourdre pour savon - Couleur Marron', 'MP', 'SICD', 'kg')
ON CONFLICT (code) DO NOTHING;
